### PR TITLE
Enhanced performance: Next Link instead of basic 'a href'

### PR DESCRIPTION
**Pull request by NoobFullStack**
Included the NextJS Link component for the page files in app and job/[slug]:
```import Link from 'next/link'```

app\page.tsx -> line 22
```<a href={`jobs/${job.slug}`}>View Job</a>```
to:
```<Link href={`jobs/${job.slug}`}>View Job</Link>```

and

jobs[slug]\page.tsx -> line 32
```<a href={'/'}>Go Back</a>```
to:
```<Link href={'/'}>Go Back</Link>```

The loading of those targets will be done on page load, providing even more performance for the website!

### CODE REVIEW

**Comment by akoskm** [comment]
Great addition, thank you! Is there anything else you'd like to add to this PR?

**Comment by NoobFullStack** [comment]
At this point I have no further additions. You can merge it if you please :)

**Comment by akoskm** [comment]
On GitHub, when you're finished with your PR, the best is to request a review from someone whose opinion could be relevant to the files you changed.

By asking for a review, you indicate that you're done with your changes, you'll have no further additions, and they are ready to be reviewed.

This helps cut down on the back and forth and land the changes faster.

You can request a review in the upper right corner of your PR by clicking "Request" next to another contributor's name.

image

If the person you want a request from is not in the list, you can click "Reviewers ⚙️," which opens up an autocomplete input of contributors.

I'm going to merge this PR. Thank you for your work!

**Comment by NoobFullStack** [comment]
> On GitHub, when you're finished with your PR, the best is to request a review from someone whose opinion could be relevant to the files you changed.
> 
> By asking for a review, you indicate that you're done with your changes, you'll have no further additions, and they are ready to be reviewed.
> 
> This helps cut down on the back and forth and land the changes faster.
> 
> You can request a review in the upper right corner of your PR by clicking "Request" next to another contributor's name.
> 
> image
> 
> If the person you want a request from is not in the list, you can click "Reviewers ⚙️," which opens up an autocomplete input of contributors.
> 
> I'm going to merge this PR. Thank you for your work!

Thanks for the guidance mate, apriciate it! Will. Use the function next time a PR arise 😁have a great weekend in advance! 🍻

**Pull request merged**
